const fs = require('fs');
const path = require('path');

const CLIENT_ID = process.env.SPOTIFY_CLIENT_ID;
const PUBLIC_BASE_URL = process.env.PUBLIC_BASE_URL || 'https://kumakitiho.github.io/Spotify-Brawser/';
const DIST_DIR = path.join(__dirname, 'dist');
const STATIC_ASSETS = [
    'shelf-mode-loader.js',
    'shelf-mode-assets.js',
    'turntable-realism.css',
    'turntable-cover-boost.css',
    'turntable-physics.css',
    'turntable-physics.js',
    'turntable-arm-detail.js',
    'turntable-polish.js',
    'turntable-reference-match.css',
    'turntable-reference-match.js',
    'turntable-no-drag.js',
    'turntable-state-guard.js',
    'turntable-live-controls.js'
];

if (!CLIENT_ID) {
    console.error('SPOTIFY_CLIENT_ID is not set');
    process.exit(1);
}

function normalizeBaseUrl(url) {
    return url.endsWith('/') ? url : url + '/';
}

function jsString(value) {
    return JSON.stringify(value);
}

function copyIfExists(file) {
    const source = path.join(__dirname, file);
    if (!fs.existsSync(source)) {
        console.warn('Skipping missing asset: ' + file);
        return;
    }
    fs.copyFileSync(source, path.join(DIST_DIR, file));
}

fs.rmSync(DIST_DIR, { recursive: true, force: true });
fs.mkdirSync(DIST_DIR, { recursive: true });

fs.copyFileSync(path.join(__dirname, 'index.html'), path.join(DIST_DIR, 'index.html'));
STATIC_ASSETS.forEach(copyIfExists);
fs.writeFileSync(path.join(DIST_DIR, '.nojekyll'), '');

const configContent = [
    '// Production config generated by build.js',
    'function loadShelfModeLoader() {',
    '    const appendLoader = () => {',
    '        const key = "shelf-mode-loader";',
    '        if (document.querySelector("script[data-shelf-mode-script=\\\"" + key + "\\\"]")) return;',
    '        const script = document.createElement("script");',
    '        script.src = "shelf-mode-loader.js?v=20260705-loader-v1";',
    '        script.defer = true;',
    '        script.dataset.shelfModeScript = key;',
    '        script.onerror = () => console.warn("Shelf Mode loader failed to load.");',
    '        document.head.appendChild(script);',
    '    };',
    '    if (document.readyState === "loading") {',
    '        document.addEventListener("DOMContentLoaded", appendLoader, { once: true });',
    '        return;',
    '    }',
    '    appendLoader();',
    '}',
    'const config = {',
    '    CLIENT_ID: ' + jsString(CLIENT_ID) + ',',
    '    REDIRECT_URI: ' + jsString(normalizeBaseUrl(PUBLIC_BASE_URL)) + ',',
    '    SCOPES: "user-top-read user-read-private user-read-email streaming user-modify-playback-state user-read-playback-state",',
    '    TOKEN_ENDPOINT: "https://accounts.spotify.com/api/token",',
    '    AUTH_URL: "https://accounts.spotify.com/authorize"',
    '};',
    'loadShelfModeLoader();',
    'window.appConfig = config;',
    ''
].join('\n');

fs.writeFileSync(path.join(DIST_DIR, 'config.js'), configContent);
console.log('dist generated: ' + normalizeBaseUrl(PUBLIC_BASE_URL));
