const fs = require('fs');
const path = require('path');

const CLIENT_ID = process.env.SPOTIFY_CLIENT_ID;
const PUBLIC_BASE_URL = process.env.PUBLIC_BASE_URL || 'https://kumakitiho.github.io/Spotify-Brawser/';
const ROOT = __dirname;
const DIST = path.join(ROOT, 'dist');

if (!CLIENT_ID) {
  console.error('SPOTIFY_CLIENT_ID is not set');
  process.exit(1);
}

function normalizeBaseUrl(url) {
  return url.endsWith('/') ? url : `${url}/`;
}

function copyDirectory(source, target) {
  fs.mkdirSync(target, { recursive: true });
  for (const entry of fs.readdirSync(source, { withFileTypes: true })) {
    const from = path.join(source, entry.name);
    const to = path.join(target, entry.name);
    if (entry.isDirectory()) copyDirectory(from, to);
    else fs.copyFileSync(from, to);
  }
}

fs.rmSync(DIST, { recursive: true, force: true });
fs.mkdirSync(DIST, { recursive: true });
fs.copyFileSync(path.join(ROOT, 'index.html'), path.join(DIST, 'index.html'));
copyDirectory(path.join(ROOT, 'src'), path.join(DIST, 'src'));
copyDirectory(path.join(ROOT, 'vinyl-cinema'), path.join(DIST, 'vinyl-cinema'));
fs.writeFileSync(path.join(DIST, '.nojekyll'), '');

const config = `// Generated by build.js\n(function () {\n  const params = new URLSearchParams(window.location.search);\n  const preview = params.get('spotifyClientId');\n  if (preview) localStorage.setItem('spotifyClientIdOverride', preview);\n  if (params.get('clearSpotifyClientId') === '1') localStorage.removeItem('spotifyClientIdOverride');\n  window.appConfig = {\n    CLIENT_ID: ${JSON.stringify(CLIENT_ID)},\n    REDIRECT_URI: ${JSON.stringify(normalizeBaseUrl(PUBLIC_BASE_URL))},\n    SCOPES: 'user-top-read user-read-private streaming user-modify-playback-state user-read-playback-state',\n    TOKEN_ENDPOINT: 'https://accounts.spotify.com/api/token',\n    AUTH_URL: 'https://accounts.spotify.com/authorize'\n  };\n})();\n`;

fs.writeFileSync(path.join(DIST, 'config.js'), config);
console.log(`Record Room build generated at ${DIST}`);
